-- migrations/devices/002_create_enrollment_codes.sql
-- Creates the devices.enrollment_codes table.
-- Enrollment codes are short-lived (10 min), single-use tokens generated by venue admin
-- to allow a new Android device to enroll in the venue.

SET search_path = devices;

CREATE TABLE IF NOT EXISTS enrollment_codes (
    code_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    venue_id   uuid NOT NULL,
    code       text UNIQUE NOT NULL,     -- short alphanumeric code displayed to admin
    created_by uuid NOT NULL,            -- venue_admin user_id that generated the code
    expires_at timestamptz NOT NULL DEFAULT now() + interval '10 minutes',
    used_at    timestamptz,
    used_by    uuid                      -- device_id that consumed this code
);

CREATE INDEX IF NOT EXISTS enrollment_codes_code_idx    ON enrollment_codes (code);
CREATE INDEX IF NOT EXISTS enrollment_codes_venue_idx   ON enrollment_codes (venue_id);
CREATE INDEX IF NOT EXISTS enrollment_codes_expires_idx ON enrollment_codes (expires_at);

GRANT SELECT, INSERT, UPDATE ON devices.enrollment_codes TO niteos_app;
